### ISSUE TITLE
Ban list will nerver update

### ISSUE THREAD

**Issue by Zelak312** [austinhuang0131/discord-ban-list-node#1]
What I want to say is that It's making one request and stop so if the code is running while the ban list update it will not update the ban list in the code (sry if this Issue is not rigth)

**Comment by austinhuang0131** [comment]
However, if I put the request module into the export one, the first result will always be inaccurate as I tested before. (The list only contains 47 IDs at the first time when the second time it has all the IDs.)

**Comment by Zelak312** [comment]
Oh kk but I looked at your code before with the request inside of the exports and I think ik why I'm pretty sure it's because of the promise because you are trying to return the array after a promise

**Comment by austinhuang0131** [comment]
#2
