### ISSUE TITLE
Always returns false

### ISSUE THREAD

**Issue by Snarr** [austinhuang0131/discord-ban-list-node#3]
I copied an ID from https://bans.discordlist.net/ and checked if it was indeed banned using

`dbl("1234567890").then(isBanned => {
    console.log(isBanned);
}).catch(console.log);`

isBanned returned false.

**Comment by austinhuang0131** [comment]
This package is no longer maintained. For DiscordList, use [this](https://www.npmjs.com/package/dban.js) instead. For the other list, this module is still useable.
